#!name=ClashCloud TikTok JP 测试
#!desc=可选模块：用于 TikTok 日本区测试，包含 TikTok 分流规则、URL Rewrite 和 MITM。启用前需要在 Shadowrocket 中安装并信任证书；如影响其他网络访问，请直接关闭本模块。
#!category=Rules

[Rule]
DOMAIN,p16-tiktokcdn-com.akamaized.net,TikTok
DOMAIN-SUFFIX,byteoversea.com,TikTok
DOMAIN-SUFFIX,ibytedtos.com,TikTok
DOMAIN-SUFFIX,ibyteimg.com,TikTok
DOMAIN-SUFFIX,ipstatp.com,TikTok
DOMAIN-SUFFIX,muscdn.com,TikTok
DOMAIN-SUFFIX,musical.ly,TikTok
DOMAIN-SUFFIX,sgpstatp.com,TikTok
DOMAIN-SUFFIX,snssdk.com,TikTok
DOMAIN-SUFFIX,tik-tokapi.com,TikTok
DOMAIN-SUFFIX,tiktok.com,TikTok
DOMAIN-SUFFIX,tiktokcdn.com,TikTok
DOMAIN-SUFFIX,tiktokv.com,TikTok
DOMAIN-KEYWORD,-tiktokcdn-com,TikTok
USER-AGENT,TikTok*,TikTok

[URL Rewrite]
(?<=_region=)CN(?=&) JP 307
(?<=&mcc_mnc=)460 440 307
^(https?:\/\/(tnc|dm)[\w-]+\.\w+\.com\/.+)(\?)(.+) $1$3 302
(^https?:\/\/*\.\w{4}okv.com\/.+&.+)(\d{2}\.3\.\d)(.+) $118.0$3 302

[MITM]
enable = true
hostname = *.tiktokv.com,*.byteoversea.com,*.tik-tokapi.com
